adding DefinitelyTyped to PR checklist
HadoukenIO/node-adapter pull request #345
Opened 2019-09-18 19:48 UTC by tomer-openfin

2019-09-18 19:49 UTC, dhamberlin approved these changes

2019-09-19 18:36 UTC, MichaelMCoates commented
@pbaize made the comment: Should we make this part of the release process rather than on a pr?

2019-09-19 18:38 UTC, pbaize requested changes
I think making this part of the pr process needs more discussion.

2019-09-27 15:24 UTC, licui3936 approved these changes

2019-11-04 19:20 UTC, closed without merging